# @package _global_

defaults:
  - _self_

# tentatively unused
offline_training:
  offline_h5_path: "data/real_robot/updated_trajs/orange_left_right_handover_{}.h5"
  
  offline_tasks: null

environment:
  cfg_name: "koch_single_task"
  text_instruction: "pick_all"
  n_envs: 1
  train_freq_num: 1
  train_freq_type: 'episode'
  ignore_language: false
  image_keys: ['observation.images.main', 'observation.images.side']
  reward_image_key: 'observation.images.main'

online_training:
  gradient_steps: 500


# Reward divisor is environment-dependent
reward_model:
  reward_divisor: 1.0