import json
import os
task_ann = {
    "assembly-v2-goal-observable": "Robot assembles the ring and the vertical stick.",
    "basketball-v2-goal-observable": "Robot puts the ball in the basket.",
    "bin-picking-v2-goal-observable": "Robot picks up the bin from the red box and places in the blue box.",
    "box-close-v2-goal-observable":  "Robot closes the box.",
    "button-press-topdown-v2-goal-observable": "Robot presses the button.",
    "button-press-topdown-wall-v2-goal-observable": "Robot presses the button behind the wall.",
    "button-press-v2-goal-observable": "Robot presses the horizontal button.",
    "button-press-wall-v2-goal-observable": "Robot avoids the wall and presses the horizontal button.",
    "coffee-button-v2-goal-observable": "Robot presses the coffee machine button.",
    "coffee-pull-v2-goal-observable": "Robot pulls the cup from the coffee machine.",
    "coffee-push-v2-goal-observable": "Robot pushes the cup into the coffee machine.",
    "dial-turn-v2-goal-observable": "Robot turns the dial.",
    "disassemble-v2-goal-observable": "Robot disassembles the ring and the vertical stick.",
    "door-close-v2-goal-observable": "Robot closes the door.",
    "door-lock-v2-goal-observable": "Robot locks the door.",
    "door-open-v2-goal-observable": "Robot opens the door.",
    "door-unlock-v2-goal-observable": "Robot unlocks the door.",
    "hand-insert-v2-goal-observable": "Robot inserts the brown square object into the hole.",
    "drawer-close-v2-goal-observable": "Robot closes the drawer.",
    "drawer-open-v2-goal-observable": "Robot opens the drawer.",
    "faucet-open-v2-goal-observable": "Robot opens the faucet.",
    "faucet-close-v2-goal-observable": "Robot closes the faucet.",
    "hammer-v2-goal-observable": "Robot uses the hammer to hit the nail.",
    "handle-press-side-v2-goal-observable": "Robot presses the handle on the side.",
    "handle-press-v2-goal-observable": "Robot presses the handle facing to it.",
    "handle-pull-side-v2-goal-observable": "Robot pulls the handle on the side.",
    "handle-pull-v2-goal-observable": "Robot pulls the handle facing to it.",
    "lever-pull-v2-goal-observable": "Robot pulls the lever.",
    "peg-insert-side-v2-goal-observable": "Robot inserts the peg into the hole on the side.",
    "pick-place-wall-v2-goal-observable": "Robot avoids the wall and picks up red object.",
    "pick-out-of-hole-v2-goal-observable": "Robot picks the red object out of the hole.",
    "reach-v2-goal-observable": "Robot moves the gripper to the target position.",
    "push-back-v2-goal-observable": "Robot pushes the brown square object back.",
    "push-v2-goal-observable": "Robot pushes the object forward.",
    "pick-place-v2-goal-observable": "Robot picks up the red object.",
    "plate-slide-v2-goal-observable": "Robot slides the plate into the soccer goal facing it.",
    "plate-slide-side-v2-goal-observable": "Robot slides the plate into the soccer goal on the side.",
    "plate-slide-back-v2-goal-observable": "Robot slides the plate back from the soccer goal facing it.",
    "plate-slide-back-side-v2-goal-observable": "Robot slides the plate back from the soccer goal on the side.",
    "peg-unplug-side-v2-goal-observable": "Robot unplugs the peg from the hole on the side.",
    "soccer-v2-goal-observable": "Robot pushes the ball into the goal.",
    "stick-push-v2-goal-observable": "Robot uses the stick and pushes the bottle.",
    "stick-pull-v2-goal-observable": "Robot uses the stick and pulls the bottle.",
    "push-wall-v2-goal-observable": "Robot pushes the red object avoiding the wall to the target position.",
    "reach-wall-v2-goal-observable": "Robot moves the gripper avoiding the wall to the target position.",
    "shelf-place-v2-goal-observable": "Robot places the blue object on the shelf.",
    "sweep-into-v2-goal-observable": "Robot sweeps the object into the hole on the table.",
    "sweep-v2-goal-observable": "Robot sweeps the object to the left side.",
    "window-open-v2-goal-observable": "Robot opens the windows, slides the window from right to left.",
    "window-close-v2-goal-observable": "Robot closes the windows, slides the window from left to right.",
}
