import json
import os
task_ann = {
    "assembly-v2": "Robot assembling",
    "basketball-v2": "Robot playing basketball",
    "bin-picking-v2": "Robot picking block",
    "box-close-v2":  "Robot closing box",
    "button-press-topdown": "Robot pressing button",
    "button-press-topdown-wall-v2": "Robot pressing button",
    "button-press-v2": "Robot pressing button",
    "button-press-wall-v2": "Robot pressing button",
    "coffee-button-v2": "Robot roasting coffee",
    "coffee-pull-v2": "Robot pulling cup",
    "coffee-push-v2": "Robot pushing cup",
    "dial-turn-v2": "Robot turning dial.",
    "disassemble-v2": "Robot disassembling",
    "door-close-v2": "Robot closing door",
    "door-lock-v2": "Robot locking door",
    "door-open-v2": "Robot opening door",
    "door-unlock-v2": "Robot unlocking door",
    "hand-insert-v2": "Robot inserting bin",
    "drawer-close-v2": "Robot closing drawer",
    "drawer-open-v2": "Robot opening drawer",
    "faucet-open-v2": "Robot opening faucet",
    "faucet-close-v2": "Robot closing faucet",
    "hammer-v2": "Robot hammering nail",
    "handle-press-side-v2": "Robot pressing handle",
    "handle-press-v2": "Robot pressing handle",
    "handle-pull-side-v2": "Robot pulling handle",
    "handle-pull-v2": "Robot pulling handle",
    "lever-pull-v2": "Robot pulling lever.",
    "peg-insert-side-v2": "Robot inserting peg",
    "pick-place-wall-v2": "Robot picking bin",
    "pick-out-of-hole-v2": "Robot picking bin",
    "reach-v2": "Robot reaching red",
    "push-back-v2": "Robot pushing bin back.",
    "push-v2": "Robot pushing bin",
    "pick-place-v2": "Robot picking bin",
    "plate-slide-v2": "Robot sliding plate",
    "plate-slide-side-v2": "Robot sliding plate",
    "plate-slide-back-v2": "Robot sliding plate",
    "plate-slide-back-side-v2": "Robot sliding plate",
    "peg-unplug-side-v2": "Robot unpluging peg",
    "soccer-v2": "Robot kicking soccer ball",
    "stick-push-v2": "Robot pushing stick",
    "stick-pull-v2": "Robot pulling stick",
    "push-wall-v2": "Robot pushing bin",
    "reach-wall-v2": "Robot reaching red",
    "shelf-place-v2": "Robot placing block to shelf",
    "sweep-into-v2": "Robot sweeping block into hole",
    "sweep-v2": "Robot sweeping block",
    "window-open-v2": "Robot opening window",
    "window-close-v2": "Robot closing window",
}
