# @package _global_

reward_model: 
  name: 'dense'
  encoder: 'dino' # default and only option is vlc
  success_bonus: 10.0

general_training:
  dense_rewards_at_end: false
  entropy_term: "auto"
  learning_rate: 1e-3
  normalize_reward: false
  terminate_on_success: false
  
environment:
  ignore_language: false