# @package _global_

reward_model: 
  name: 'dense'
  encoder: 'dino' # default and only option is vlc
  success_bonus: 50.0
  general_training:
    dense_rewards_at_end: true
    entropy_term: "auto"
    learning_rate: 1e-3
  environment:
    ignore_language: true