# @package _global_

reward_model: 
  name: 'rewind'
  batch_size: 64
  model_path: '/home/jzhang96/RoboCLIPv2/scripts/metaworld_5_Demo_PosEmb_View_side_OpenX_Rewind_ratio_0.8_EMA_momentum_0.3_End_Rewind_ratio_0.1/model_20.pth'
  use_pca: false
  success_bonus: 10
  reward_divisor: 1
  reward_at_every_step: true
  sum_reward: false
  
general_training:
  dense_rewards_at_end: false
  learning_rate: 1e-3
  entropy_term: "auto"
  normalize_reward: true
  terminate_on_success: false
# environment:
#   is_state_based: false

# offline_training:
#   offline_training_steps: 1

# data/h5_buffers/updated_trajs/metaworld_traj_15_demos_roboclipv2.h5