# @package _global_

reward_model: 
  name: 'rewind'
  batch_size: 64
  model_path: '/project2/biyik_1165/haobaizh/rewind_valuemodel/checkpoints/rewind_metaworld_epoch_19.pth'
  use_pca: false
  success_bonus: 200
  reward_divisor: 1
  reward_at_every_step: true
  sum_reward: false
  use_progress_diff: false
  use_reverse_progress_diff: false
  diff_gamma: 1.0
  diff_reward_scale: 1.0
  use_base_reward: false
  base_reward_value: -1.0
  
general_training:
  dense_rewards_at_end: false
  learning_rate: 1e-3
  entropy_term: "auto"
  normalize_reward: false
  terminate_on_success: true
  # resume_ckpt_path: "/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-04-29/18-22-23/logs/rewind_rlpd_handle-press-side-v2_final/best_model"
# environment:
#   is_state_based: false

# offline_training:
#   offline_training_steps: 1

# data/h5_buffers/updated_trajs/metaworld_traj_15_demos_roboclipv2.h5
