# @package _global_

general_training:
  dense_rewards_at_end: false


reward_model: 
  name: 'rewind'
  batch_size: 64
  model_path: "/scr2/yusenluo/RoboCLIPv2/models/reward_model/rewind_model/model_27.pth"
  reward_at_every_step: true
  camera_names: ["observation.images.main"]


  success_bonus: 64

environment:
  is_state_based: false
  reward_image_key: 'observation.images.main'

# environment:
#   is_state_based: false

# offline_training:
#   offline_training_steps: 1

# data/h5_buffers/updated_trajs/metaworld_traj_15_demos_roboclipv2.h5