# @package _global_

general_training:
  dense_rewards_at_end: false
  learning_rate: 1e-3
  entropy_term: "auto"
  normalize_reward: false
  terminate_on_success: true

reward_model:
  name: 'topreward'
  model_path: 'none'
  batch_size: 1
  success_bonus: 0
  reward_divisor: 1
  reward_at_every_step: true
  sum_reward: false
  use_progress_diff: false
  use_reverse_progress_diff: false
  diff_gamma: 1.0
  diff_reward_scale: 1.0
  use_base_reward: false
  base_reward_value: -1.0

  max_frames: 4
  server_url: 'http://localhost:8000'
  vlm_model_name: 'Qwen/Qwen3-VL-8B-Instruct'
  request_timeout: 900
  request_retries: 3
  lock_path: ''
