# @package _global_

defaults:
  - _self_

general_training:
  algo: bc
  name: bc
  action_noise: 0 # sigma
  learning_rate: 3e-4

model:
  policy_layer_norm: true
  critic_layer_norm: true
  pi_net_arch: [1024, 512, 256]
  qf_net_arch: [1024, 512, 512]

offline_training:
  offline_training_steps: 50000 

online_training:
  total_time_steps: 0