# @package _global_

defaults:
  - _self_

# Because RLPD is slower, we will log more frequently
logging:
  eval_freq: 10000
  video_freq: 10000

general_training:
  algo: rlpd
  name: wsrl_iql
  action_noise: 0.0 # sigma
  learning_rate: 1e-4

  # offline rl parameters
  n_critics: 5
  n_critics_to_sample: 2

  # RLPD-specific parameters
  rlpd_train_critic_with_entropy: false
  entropy_term: 'auto'
  # Note: RLPD's offline step uses default params defined in base_config.yaml
  rlpd_offline_algo: iql
  action_chunk_size: 60

  # IQL-specific parameters
  policy_extraction: 'awr' # awr or ddpg
  awr_advantage_temp: 1.0 # iql only

  learning_starts: 5

model:
  policy_layer_norm: false
  critic_layer_norm: false
  pi_net_arch: [768, 512, 256]
  qf_net_arch: [768, 512, 256]

offline_training:
  offline_training_steps: 100000
  ckpt_path: "/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-28/10-39-12/logs/rewind_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_rebuttal_flint/last_offline"
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-30/23-36-17/logs/rewind_rlpd_button-press-wall-v2_rebuttal_flint_full_pe_ablation/last_offline" #full pe ablation
   #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-30/21-15-21/logs/rewind_rlpd_button-press-wall-v2_rebuttal_flint_5_task_ablation/last_offline" # 5 task ablation
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-30/14-38-44/logs/rewind_rlpd_button-press-wall-v2_rebuttal_flint_10_task_ablation/last_offline" # 10 task ablation
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-30/13-09-22/logs/rewind_rlpd_button-press-wall-v2_rebuttal_flint_no_rewind_ablation/last_offline" # no rewind ablation
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-28/10-39-12/logs/rewind_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_rebuttal_flint/last_offline"
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-29/23-59-04/logs/sparse_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_rebuttal_flint/last_offline" # 15k false n_critics 5 sparse
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-28/10-39-12/logs/rewind_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_rebuttal_flint/last_offline" # 15k false n_critics 5 rewind
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-28/03-33-53/logs/rewind_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_rebuttal_flint/last_offline" # 5k false n_critics 10
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-23/23-00-21/logs/rewind_rlpd_window-close-v2_entropy_auto_layer_norm_False_bonus_64/last_offline" # 5k false 512
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-23/01-40-02/logs/rewind_rlpd_window-close-v2_entropy_auto_layer_norm_True_bonus_64/last_offline" #8k true 
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-23/01-26-16/logs/rewind_rlpd_window-close-v2_entropy_auto_layer_norm_False_bonus_64/last_offline" 5k false 
  #"/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/outputs/2025-06-12/07-11-34/logs/rewind_rlpd_button-press-wall-v2_entropy_auto_layer_norm_False_bonus_64/last_offline" 12k false 
  critic_update_ratio: 1

online_training:
  total_time_steps: 100000
  mix_buffers_ratio: 0.5 # WSRL does not use old replay buffer
  warm_start_online_rl: true # main change for WSRL
  learning_starts: 4000
  gradient_steps: 75
  critic_update_ratio: 4