wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/visualization/decoder_only/eval_GVL.py
    python_version: 3.8.16
    cli_version: 0.16.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737421763.06401
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.8.16
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
