import json
import os
task_ann = {
    "assembly-v2-goal-hidden": "assembling",
    "basketball-v2-goal-hidden": "playing basketball",
    "bin-picking-v2-goal-hidden": "Picking bin",
    "box-close-v2-goal-hidden":  "closing box",
    "button-press-topdown-v2-goal-hidden": "pressing button",
    "button-press-topdown-wall-v2-goal-hidden": "pressing button",
    "button-press-v2-goal-hidden": "pressing button",
    "button-press-wall-v2-goal-hidden": "pressing button",
    "coffee-button-v2-goal-hidden": "roasting coffee",
    "coffee-pull-v2-goal-hidden": "pulling cup",
    "coffee-push-v2-goal-hidden": "pushing cup",
    "dial-turn-v2-goal-hidden": "turning dial.",
    "disassemble-v2-goal-hidden": "disassembling",
    "door-close-v2-goal-hidden": "closing door",
    "door-lock-v2-goal-hidden": "locking door",
    "door-open-v2-goal-hidden": "opening door",
    "door-unlock-v2-goal-hidden": "unlocking door",
    "hand-insert-v2-goal-hidden": "inserting bin",
    "drawer-close-v2-goal-hidden": "closing drawer",
    "drawer-open-v2-goal-hidden": "opening drawer",
    "faucet-open-v2-goal-hidden": "opening faucet",
    "faucet-close-v2-goal-hidden": "closing faucet",
    "hammer-v2-goal-hidden": "hammering nail",
    "handle-press-side-v2-goal-hidden": "pressing handle",
    "handle-press-v2-goal-hidden": "pressing handle",
    "handle-pull-side-v2-goal-hidden": "pulling handle",
    "handle-pull-v2-goal-hidden": "pulling handle",
    "lever-pull-v2-goal-hidden": "pulling lever.",
    "peg-insert-side-v2-goal-hidden": "inserting peg",
    "pick-place-wall-v2-goal-hidden": "picking bin",
    "pick-out-of-hole-v2-goal-hidden": "picking bin",
    "reach-v2-goal-hidden": "reaching red",
    "push-back-v2-goal-hidden": "pushing bin back.",
    "push-v2-goal-hidden": "pushing bin",
    "pick-place-v2-goal-hidden": "picking bin",
    "plate-slide-v2-goal-hidden": "sliding plate",
    "plate-slide-side-v2-goal-hidden": "sliding plate",
    "plate-slide-back-v2-goal-hidden": "sliding plate",
    "plate-slide-back-side-v2-goal-hidden": "sliding plate",
    "peg-unplug-side-v2-goal-hidden": "unpluging peg",
    "soccer-v2-goal-hidden": "kicking soccer ball",
    "stick-push-v2-goal-hidden": "pushing stick",
    "stick-pull-v2-goal-hidden": "pulling stick",
    "push-wall-v2-goal-hidden": "pushing bin",
    "reach-wall-v2-goal-hidden": "reaching red",
    "shelf-place-v2-goal-hidden": "placing bin to shelf",
    "sweep-into-v2-goal-hidden": "sweeping bin",
    "sweep-v2-goal-hidden": "sweeping bin",
    "window-open-v2-goal-hidden": "opening window",
    "window-close-v2-goal-hidden": "closing window",
}
