# @package _group_
defaults:
  - _self_

wandb_notes: ""

logging:
  wandb: true
  wandb_entity_name: "clvr"
  wandb_project_name: "roboclip-v2"
  wandb_group_name: "${general_training.algo}_sparse_${general_training.sparse_only}"
  log_dir: "./logs/baseline_logs/${logging.wandb_group_name}$"
  eval_freq: 5000
  video_freq: 50000

general_training:
  algo: "iql"
  n_steps: 128
  seed: 42
  sparse_only: true
  pretrained: false
  acion_noise: null
  learning_rate: 1e-4

  # IQL-specific parameters
  policy_extraction: 'awr' # awr or ddpg
  awr_advantage_temp: 5.0 # iql only
  ddpg_bc_weight: 0.1 # iql only
  critic_update_ratio: 1 # iql and cql

  # below not used for now
  succ_end: false
  random_reset: false
  norm_input: false
  norm_output: false
  time_reward: 1.0
  threshold_reward: false
  entropy_term: "auto" # ppo only
  time_penalty: 0.0


online_training:
  total_time_steps: 1000000
  mix_buffers: true

offline_training:
  offline_h5_path: "data/h5_buffers/updated_trajs/metaworld_traj_100_demos_orig_reward.h5"
  offline_training_steps: 100000
  offline_tasks: ["opening window"]
  succ_bonus: 10.0

model:
  policy_layer_norm: true
  critic_layer_norm: true
  pi_net_arch: [256, 256]
  qf_net_arch: [256, 256]

environment:
  n_envs: 3
  train_freq_num: 1
  train_freq_type: 'step'
  text_string: "opening window"
  dir_add: ""
  video_path: null
  pca_path: null
  transform_base_path: null
  transform_model_path: null
  ignore_language: false
  use_simulator_reward: true
  succ_bonus: 10.0
