# @package _group_

defaults:
  - base_config
  - _self_

general_training:
  algo: iql
  action_noise: 0.1 # sigma
  sparse_only: false

  # IQL-specific parameters
  policy_extraction: 'ddpg' # awr or ddpg
  awr_advantage_temp: 5.0 # iql only
  ddpg_bc_weight: 0. # iql only
  critic_update_ratio: 4 # iql and cql

model:
  policy_layer_norm: false
  critic_layer_norm: false
  pi_net_arch: [512, 256]
  qf_net_arch: [512, 256]

offline_training:
  offline_h5_path: 'data/h5_buffers/updated_trajs/metaworld_window_traj_orig_reward.h5'
  offline_tasks: ["opening window"]
  offline_training_steps: 0

online_training:
  total_time_steps: 1000000

environment:
  n_envs: 1
  train_freq_num: 1
  train_freq_type: 'step'
  text_string: "opening window"
  ignore_language: true
