# @package _global_

defaults:
  - _self_


offline_training:
  offline_h5_path: "data/h5_buffers/updated_trajs/metaworld_traj_100_demos_{}.h5"
  offline_tasks: "all"
  offline_training_steps: 5000 

online_training:
  total_time_steps: 1000000

environment:
  cfg_name: "metaworld_all_tasks_100"
  n_envs: 1
  train_freq_num: 1
  train_freq_type: 'step'
  env_id: "window-open-v2" # eval task
  ignore_language: false

# Reward divisor is environment-dependent
reward_model:
  reward_divisor: 1.0