# @package _global_

defaults:
  - _self_

offline_training:
  offline_h5_path: "/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/scripts/metaworld_policy_pretrain_dataset_rewind_dense.h5" #
  offline_tasks: ['button-press-v2', 'button-press-topdown-wall-v2', 'coffee-pull-v2', 'dial-turn-v2', 'door-open-v2',
                  'door-unlock-v2', 'drawer-close-v2', 'faucet-open-v2', 'handle-press-v2', 'handle-pull-side-v2',
                  'peg-insert-side-v2', 'pick-place-v2', 'plate-slide-v2', 'plate-slide-back-side-v2', 'push-v2',
                  'reach-v2', 'stick-push-v2', 'stick-pull-v2', 'window-open-v2', 'hand-insert-v2']
  ckpt_path: "/home/yusenluo/RoboCLIP_offline/RoboCLIPv2/models/reward_model/pretrained_rewind/rewind_dense_100k.zip"

online_training:
  total_time_steps: 100000

general_training:
  seed: 42

environment:
  cfg_name: "metaworld_off_on_15"
  n_envs: 1
  train_freq_num: 1
  train_freq_type: 'step'
  env_id: "handle-press-side-v2" # eval task
  ignore_language: false

# Reward divisor is environment-dependent
reward_model:
  reward_divisor: 1

# /home/jzhang96/RoboCLIPv2/outputs/2025-04-20/00-08-09/logs/small_model_sparse_iql/last_offline