# @package _global_

defaults:
  - _self_


offline_training:
  offline_h5_path: "data/h5_buffers/updated_trajs/metaworld_traj_15_demos_{}.h5"
  offline_tasks: ["window-open-v2"]
  offline_training_steps: 10000 

online_training:
  total_time_steps: 1000000

environment:
  cfg_name: "metaworld_single_task"
  n_envs: 1
  train_freq_num: 1
  train_freq_type: 'step'
  env_id: "window-open-v2"
  ignore_language: false

# Reward divisor is environment-dependent
reward_model:
  reward_divisor: 1.0